services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    network_mode: host
    command: postgres -p 5433
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
